// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2974.SoccerBot.subsystems;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc2974.SoccerBot.RobotMap;
import org.usfirst.frc2974.SoccerBot.commands.IntakeFlat;
import org.usfirst.frc2974.SoccerBot.commands.IntakeManual;


/**
 * Abstract class for use with Intake or IntakeNoPotentiometer
 */
abstract public class AbstractIntake extends Subsystem {

  private final Solenoid extend = RobotMap.intakeArmExtend;
  private final TalonSRX armTalon = RobotMap.intakeArmTalon;
  private final Solenoid retract = RobotMap.intakeArmRetract;
  //protected IntakeFlat flatCommand = new IntakeFlat();
  private ArmMovement action;

  public void updateSmartDashboard() {
    SmartDashboard.putString("arm movement", action.toString());
    SmartDashboard.putString("Arm position", getArmPosition().toString());
  }

  public void initDefaultCommand() {
    setDefaultCommand(new IntakeManual());
  }

  public void startFlat() {
    new IntakeFlat().start();
  }

  public void endFlat() {
    new IntakeManual().start();
  }

  //sets solenoid values to true/false depending on case
  public void setArmMovement(ArmMovement move) {
    switch (move) {
      case FALL:
        extend.set(true);
        retract.set(false);
        break;
      case UP:
        extend.set(false);
        retract.set(true);
        break;
      case BLOCK:
        extend.set(false);
        retract.set(false);
        break;
    }
    action = move;
  }

  public ArmMovement getAction() {
    return action;
  }

  /**
   * sets speed of motor on intake arm
   *
   * @param speed da speed
   */
  public void setMotorPower(double speed) {
    armTalon.set(ControlMode.PercentOutput, speed);
  }

  abstract public ArmPosition getArmPosition();

  //enumerates the two cases used later; UP, and FALL
  public enum ArmMovement {
    UP, FALL, BLOCK
  }

  public enum ArmPosition {
    UP, HIGH, DRIBBLE, LOW, FLAT
  }
}

