// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2974.SoccerBot;

import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import org.usfirst.frc2974.SoccerBot.commands.ToggleCharge;

/**
 * This class is the glue that binds the controls on the physical operator interface to the commands and command groups
 * that allow control of the robot.
 */
public class OI {

  public final Gamepad xbox;
  public final Button kickButton;
  public final Button readyButton;
  public final Button dribbleButton;
  public final Button loadButton;
  public final Button flatButton;
  public final Button discharge;
  public final Button adjustArm;
  public final Button manualButton;
  private final Button chargeSwitch;

  public OI() {
    xbox = new Gamepad(0);
    // buttons
    kickButton = new JoystickButton(xbox, Gamepad.Button.A.getIndex());
    readyButton = new JoystickButton(xbox, Gamepad.Button.B.getIndex());
    adjustArm = new JoystickButton(xbox, Gamepad.Button.X.getIndex());
    flatButton = new JoystickButton(xbox, Gamepad.Button.L.getIndex());
    manualButton = new JoystickButton(xbox, Gamepad.Button.R.getIndex());
    dribbleButton = new JoystickButton(xbox, Gamepad.Button.BACK.getIndex());
    loadButton = new JoystickButton(xbox, Gamepad.Button.START.getIndex());
    discharge = new JoystickButton(xbox, 9);
    chargeSwitch = new JoystickButton(xbox, 10);

    chargeSwitch.whenPressed(new ToggleCharge());
  }
}
